# Generated by Django 3.1.7 on 2021-06-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210610_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
